In [1]:
import pandas as pd
import numpy as np

Task 1 — Load and Explore

In [4]:
# Load CSV into DataFrame and Print the first 5 rows
df = pd.read_csv("data/trends_clean.csv")
print("First 5 rows:")
df.head(5)

First 5 rows:

,post_id,title,category,score,num_comments,author,collected_at
0,47762864,Backblaze has stopped backing up your data,technology,277,185,rrreese,2026-04-14 17:47:28.177632
1,47761625,Multi-Agentic Software Development Is a Distri...,technology,50,17,tie-in,2026-04-14 17:48:05.420530
2,47761723,MOS tech 6502 8-bit microprocessor in pure SQL...,technology,36,3,adunk,2026-04-14 17:48:08.676760
3,47758347,N-Day-Bench – Can LLMs find real vulnerabiliti...,technology,78,26,mufeedvh,2026-04-14 17:48:35.050733
4,47728970,"Write less code, be more responsible",technology,109,65,orhunp_,2026-04-14 17:48:38.310662

In [3]:
#Shape 
print(f"Loaded data: {df.shape}")

Loaded data: (90, 7)

In [5]:
# Average score and comments
avg_score = df["score"].mean()
avg_comments = df["num_comments"].mean()

print(f"\nAverage score   : {avg_score:.2f}")
print(f"Average comments: {avg_comments:.2f}")

Average score   : 186.32
Average comments: 87.52

Task 2 — Basic Analysis with NumPy

In [6]:
scores = df["score"].values
comments = df["num_comments"].values

# Mean, Median, Std
print(f"Mean score   : {np.mean(scores):.2f}")
print(f"Median score : {np.median(scores):.2f}")
print(f"Std deviation: {np.std(scores):.2f}")

Mean score   : 186.32
Median score : 77.00
Std deviation: 327.38

In [7]:
# Max and Min
print(f"Max score    : {np.max(scores)}")
print(f"Min score    : {np.min(scores)}")

Max score    : 2325
Min score    : 5

In [10]:
# Category with most stories
top_category = df["category"].mode()[0]
top_count = (df["category"] == top_category).sum()

print(f"\nMost stories in: {top_category} ({top_count} stories)")

Most stories in: entertainment (25 stories)

In [11]:
# Most commented story
max_comments_idx = np.argmax(comments)
top_story = df.iloc[max_comments_idx]

print(f"\nMost commented story: \"{top_story['title']}\" — {top_story['num_comments']} comments")

Most commented story: "Filing the corners off my MacBooks" — 669 comments

Task 3 — Add New Columns

In [12]:
# Engagement formula
df["engagement"] = df["num_comments"] / (df["score"] + 1)

# Popular flag
df["is_popular"] = df["score"] > avg_score

In [13]:
df.head(5)

,post_id,title,category,score,num_comments,author,collected_at,engagement,is_popular
0,47762864,Backblaze has stopped backing up your data,technology,277,185,rrreese,2026-04-14 17:47:28.177632,0.665468,True
1,47761625,Multi-Agentic Software Development Is a Distri...,technology,50,17,tie-in,2026-04-14 17:48:05.420530,0.333333,False
2,47761723,MOS tech 6502 8-bit microprocessor in pure SQL...,technology,36,3,adunk,2026-04-14 17:48:08.676760,0.081081,False
3,47758347,N-Day-Bench – Can LLMs find real vulnerabiliti...,technology,78,26,mufeedvh,2026-04-14 17:48:35.050733,0.329114,False
4,47728970,"Write less code, be more responsible",technology,109,65,orhunp_,2026-04-14 17:48:38.310662,0.590909,False

In [14]:
# Step 4 — Save Result

df.to_csv("data/trends_analysed.csv", index=False)

print(f"\nSaved to {"data/trends_analysed.csv"}")

Saved to data/trends_analysed.csv